In [28]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer
from sklearn.decomposition import NMF
art = pd.read_pickle("data/articles.pkl")
snowball = SnowballStemmer('english')
import random 


In [10]:
def tokenize(doc):
    return [snowball.stem(word) for word in word_tokenize(doc.lower())]

content = art.content
cv = TfidfVectorizer(max_features=5000, stop_words='english', tokenizer=tokenize)
mtx = cv.fit_transform(content)
wdindex= cv.vocabulary_

In [27]:
v=mtx.toarray()
model = NMF(n_components=10, init='random', random_state=0, max_iter=100)
model.fit_transform(v)
model.components_

array([[ 0.11852578,  0.01279904,  0.        , ...,  1.45312301,
         1.76783098,  1.10814498],
       [ 0.00388432,  0.00843175,  0.        , ...,  0.27473598,
         0.18147669,  0.11790743],
       [ 0.0205858 ,  0.00399839,  0.        , ...,  0.47609201,
         0.24631037,  0.13813207],
       ..., 
       [ 0.00581732,  0.01094559,  0.        , ...,  0.17087651,
         0.10285741,  0.07667402],
       [ 0.02376135,  0.        ,  0.        , ...,  0.28518338,
         0.06013246,  0.00277476],
       [ 0.010218  ,  0.        ,  0.        , ...,  0.36726843,
         0.197677  ,  0.09377298]])

In [15]:
inv_wdindex = {v: k for k, v in wdindex.iteritems()}
inv_wdindex

{0: u'.',
 1: u'...',
 2: u'0-3',
 3: u'0-4',
 4: u'0.1',
 5: u'0.4',
 6: u'1,000',
 7: u'1-0',
 8: u'1-1',
 9: u'1-2',
 10: u'1-3',
 11: u'1.2',
 12: u'1.4',
 13: u'10',
 14: u'10,000',
 15: u'10-year',
 16: u'100',
 17: u'100,000',
 18: u'10:30',
 19: u'10th',
 20: u'11',
 21: u'12',
 22: u'120',
 23: u'12th',
 24: u'13',
 25: u'13th',
 26: u'14',
 27: u'14th',
 28: u'15',
 29: u'150',
 30: u'16',
 31: u'17',
 32: u'18',
 33: u'18,000',
 34: u'18-49',
 35: u'18th',
 36: u'19',
 37: u'1913',
 38: u'1938',
 39: u'1950s',
 40: u'1960s',
 41: u'1963',
 42: u'1964',
 43: u'1965',
 44: u'1966',
 45: u'1968',
 46: u'1970',
 47: u'1970s',
 48: u'1971',
 49: u'1972',
 50: u'1973',
 51: u'1975',
 52: u'1978',
 53: u'1979',
 54: u'1980',
 55: u'1980s',
 56: u'1982',
 57: u'1983',
 58: u'1984',
 59: u'1985',
 60: u'1986',
 61: u'1987',
 62: u'1989',
 63: u'1990',
 64: u'1990s',
 65: u'1991',
 66: u'1992',
 67: u'1993',
 68: u'1994',
 69: u'1995',
 70: u'1996',
 71: u'1997',
 72: u'1998',
 73: u'

In [26]:
lst=[]
for i in range(10):
    print [inv_wdindex[j] for j in [arr.argsort()[-10:][::-1] for arr in model.components_][i]]

[u'\u201c', u'\u2019', u'\u201d', u's', u'said', u't', u'like', u'peopl', u'new', u'time']
[u'iran', u'rouhani', u'nuclear', u'mr.', u'iranian', u'obama', u'israel', u'netanyahu', u's', u'\u2019']
[u'republican', u'hous', u'senat', u'health', u'govern', u'care', u'obama', u'shutdown', u'law', u'\u2019']
[u'game', u'\u2019', u'yanke', u'season', u'team', u'rivera', u's', u'leagu', u'play', u'inning']
[u'\u2019', u's', u'music', u'mr.', u'art', u'\u201c', u'danc', u'perform', u'opera', u'ballet']
[u'race', u'cup', u'team', u'oracl', u'\u2019', u'zealand', u's', u'boat', u'yacht', u'america']
[u'attack', u'kill', u'said', u'mall', u'kenya', u'offici', u'kenyan', u'polic', u'shabab', u'milit']
[u'syria', u'chemic', u'weapon', u'syrian', u'unit', u'resolut', u'council', u'russia', u'nation', u'secur']
[u'percent', u'bank', u'compani', u'market', u'rate', u'china', u'said', u'govern', u'economi', u'year']
[u'parti', u'mr.', u'merkel', u's', u'court', u'\u2019', u'polit', u'elect', u'democrat

In [39]:
w= np.random.sample(1405*10).reshape(1405,10)

In [52]:
h = np.random.sample(5000*10).reshape(10,5000)
type(h)

numpy.ndarray

In [59]:
h,_,_,_=np.linalg.lstsq(w,v)
h

array([[ 0.00156953,  0.00041593,  0.00051629, ...,  0.01259939,
         0.01551939,  0.01015764],
       [ 0.00253031, -0.00082621,  0.00082845, ...,  0.0191923 ,
         0.0089006 ,  0.00436759],
       [ 0.00247545, -0.00146477,  0.00045518, ...,  0.02040677,
         0.01601989,  0.00963988],
       ..., 
       [ 0.00213807,  0.00143513, -0.0012899 , ...,  0.01317283,
         0.0156413 ,  0.00691585],
       [ 0.00143383, -0.00061398,  0.00048999, ...,  0.02062366,
         0.00826951,  0.00424131],
       [-0.00273303,  0.00034301,  0.00167412, ...,  0.01215393,
         0.01432041,  0.00940717]])

In [61]:
h = h.clip(min=0)
h

array([[ 0.00156953,  0.00041593,  0.00051629, ...,  0.01259939,
         0.01551939,  0.01015764],
       [ 0.00253031,  0.        ,  0.00082845, ...,  0.0191923 ,
         0.0089006 ,  0.00436759],
       [ 0.00247545,  0.        ,  0.00045518, ...,  0.02040677,
         0.01601989,  0.00963988],
       ..., 
       [ 0.00213807,  0.00143513,  0.        , ...,  0.01317283,
         0.0156413 ,  0.00691585],
       [ 0.00143383,  0.        ,  0.00048999, ...,  0.02062366,
         0.00826951,  0.00424131],
       [ 0.        ,  0.00034301,  0.00167412, ...,  0.01215393,
         0.01432041,  0.00940717]])

In [65]:
w,_,_,_=np.linalg.lstsq(v.T,h.T)
w = w.clip(min=0)
w

array([[ 0.00064178,  0.        ,  0.        , ...,  0.00010839,
         0.        ,  0.00196983],
       [ 0.00328746,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.00183021],
       [ 0.00269655,  0.        ,  0.00031501, ...,  0.00454128,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.0088981 ,
         0.00349887,  0.00310689],
       [ 0.        ,  0.00280163,  0.00034439, ...,  0.0027536 ,
         0.00136291,  0.        ],
       [ 0.00168787,  0.00306743,  0.00317445, ...,  0.00255471,
         0.00052073,  0.        ]])